-- MySQL Script generated by MySQL Workbench
-- Mon Mar 28 21:49:30 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema articles_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `articles_db` ;

-- -----------------------------------------------------
-- Schema articles_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `articles_db` DEFAULT CHARACTER SET utf8 ;
USE `articles_db` ;

-- -----------------------------------------------------
-- Table `articles_db`.`Roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `articles_db`.`Roles` ;

CREATE TABLE IF NOT EXISTS `articles_db`.`Roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `articles_db`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `articles_db`.`Users` ;

CREATE TABLE IF NOT EXISTS `articles_db`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(155) NOT NULL,
  `summary` TEXT NULL,
  `Roles_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_Users_Roles1_idx` (`Roles_id` ASC) VISIBLE,
  CONSTRAINT `fk_Users_Roles1`
    FOREIGN KEY (`Roles_id`)
    REFERENCES `articles_db`.`Roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `articles_db`.`Articles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `articles_db`.`Articles` ;

CREATE TABLE IF NOT EXISTS `articles_db`.`Articles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(155) NOT NULL,
  `content` TEXT NOT NULL,
  `publishedAt` DATETIME NOT NULL,
  `summary` VARCHAR(100) NULL,
  `Users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Articles_Users1_idx` (`Users_id` ASC) VISIBLE,
  CONSTRAINT `fk_Articles_Users1`
    FOREIGN KEY (`Users_id`)
    REFERENCES `articles_db`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `articles_db`.`Comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `articles_db`.`Comments` ;

CREATE TABLE IF NOT EXISTS `articles_db`.`Comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT NOT NULL,
  `publishedAt` DATETIME NOT NULL,
  `Articles_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Comments_Articles1_idx` (`Articles_id` ASC) VISIBLE,
  CONSTRAINT `fk_Comments_Articles1`
    FOREIGN KEY (`Articles_id`)
    REFERENCES `articles_db`.`Articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `articles_db`.`Categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `articles_db`.`Categories` ;

CREATE TABLE IF NOT EXISTS `articles_db`.`Categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `articles_db`.`Articles_has_Categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `articles_db`.`Articles_has_Categories` ;

CREATE TABLE IF NOT EXISTS `articles_db`.`Articles_has_Categories` (
  `Articles_id` INT NOT NULL,
  `Categories_id` INT NOT NULL,
  PRIMARY KEY (`Articles_id`, `Categories_id`),
  INDEX `fk_Articles_has_Categories_Categories1_idx` (`Categories_id` ASC) VISIBLE,
  INDEX `fk_Articles_has_Categories_Articles_idx` (`Articles_id` ASC) VISIBLE,
  CONSTRAINT `fk_Articles_has_Categories_Articles`
    FOREIGN KEY (`Articles_id`)
    REFERENCES `articles_db`.`Articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articles_has_Categories_Categories1`
    FOREIGN KEY (`Categories_id`)
    REFERENCES `articles_db`.`Categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
